config/routes.rb
Rails.application.routes.draw do
  root 'users#home'
  get 'tasks/show:id', to: 'tasks#show', as: 'show_task'
  get 'task/new/:id', to: 'tasks#new' , as: 'tasks_new_id'
  get 'tasks/edit/:id' , to: 'tasks#edit' , as: 'edit_task'
  post 'tasks/update/:id' , to: 'tasks#update' , as: 'tasks_update'
  delete 'tasks/destroy/:id' , to: 'tasks#destroy' , as: 'destroy_task'
  post 'tasks/create/:id', to: 'tasks#create' , as: 'create_task'

  get '/today_tasks/:id', to: 'today_tasks#index', as: 'today_tasks'

  get 'categories/new/:id', to: "categories#new" , as: 'categories_new'
  get 'categories/:id', to: 'categories#show', as: 'show_tasks'
  post 'categories/create/:id', to: 'categories#create', as: 'categories_create'
  get 'categories/edit/:id', to: 'categories#edit' , as: 'categories_edit'
  post 'categories/update/:id', to: 'categories#update' , as: 'categories_update'
  # get 'categories/destroy'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
 

  get  '/home',   to: 'users#home', as: "home"

   
  resources :users

end

app/models/task.rb
class Task < ApplicationRecord
    validates :description, :completed_at, presence: true
    belongs_to :category
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def show
    time = Time.now 
    @today_task_count = Task.where("DATE(completed_at) = ?", time.strftime("%Y-%m-%d") ).count
    @category_id = Category.find(params[:category_id])
    @user_id = User.find(params[:user_id])
    @task_id = Task.find(params[:id])
    @tasks = Task.joins(:category).where( :id => @task_id )
  end

  def new
    time = Time.now 
    @today_task_count = Task.where("DATE(completed_at) = ?", time.strftime("%Y-%m-%d") ).count
    @category_id = Category.find(params[:id])
    @user_id = User.find(params[:user_id])
  end

  def edit
    @category_id = Category.find(params[:category_id])
    time = Time.now 
    @today_task_count = Task.where("DATE(completed_at) = ?", time.strftime("%Y-%m-%d") ).count
    @user_id = User.find(params[:user_id])
    @task_id = Task.find(params[:id])
  end

  def create
    @category_id = Category.find(params[:id])
    @task_create = Task.create(description: params[:description],completed: params[:completed], completed_at: params[:completed_at] ,category_id: params[:category_id] ) 
    @user_id = User.find(params[:user_id])
    if @task_create.save
      redirect_to show_tasks_path(@category_id,user_id: @user_id), :flash => { :success => "Successfull added new task" }
    else
      redirect_to show_tasks_path(@category_id,user_id: @user_id), :flash => {:alert => "Unabled to add task"}
    end
  end

  def update
    @task = Task.find(params[:id])
    @user_id = User.find(params[:user_id])
    @task.update(description: params[:description],completed: params[:completed], completed_at: params[:completed_at])
      # redirect_to show_tasks_path(@category_id,user_id: @user), :flash => { :success => "Successfull updated new task" }
    
  end

  def destroy
    @task = Task.find(params[:id])
    @user_id = User.find(params[:user_id])
    @category_id = Category.find(params[:category_id])
    @task.destroy
      redirect_to show_tasks_path(@category_id,user_id: @user_id), :flash => { :success => "Successfull Deleted" }
  end

  def index
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/destroy.html.erb
<h1>Tasks#destroy</h1>
<p>Find me in app/views/tasks/destroy.html.erb</p>

app/views/tasks/edit.html.erb
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
       <%= link_to show_tasks_path(@category_id,user_id: @user_id) do%>
      <i class="fas fa-backward"></i>
    <% end %>       
        <h1>Edit task
        
        </h1>
            <%= form_with url: tasks_update_path(category_id:@category_id,user_id:@user_id) do |f| %>
                <div class="form-group">
                <p> 
                    <%= f.label :description %> <br/>
                    <%= f.text_area :description ,class: "form-control", size: "30x10", value: @task_id.description%>
                </p>
                <p> 
                 <p> 
                    <%= f.label :sched_date_field, "Deadline" %>
                    <%= f.text_field :completed_at, :class => "form-control", value:@task_id.completed_at %>
                </p> 
                <p> 
                    <%= f.label :sched_date_field, "New Deadline" %>
                    <%= f.datetime_field :completed_at, :class => "datepicker form-control", value:@task_id.completed_at %>
                </p>
                <p> 
                    <%= f.submit class: "btn btn-primary my-2"%>
                </p>

            <% end%>
              </div>
      </div>
    </div>

app/views/tasks/index.html.erb
<h1>Tasks#index</h1>
<p>Find me in app/views/tasks/index.html.erb</p>

app/views/tasks/new.html.erb
<main>
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">      
        <h1>Create Task</h1>
            <%= form_with url: create_task_path(@category_id,user_id:@user_id) do |f| %>
                <div class="form-group">
                <p> 
                    <%= f.label :description %> <br/>
                    <%= f.text_area :description ,class: "form-control", size: "30x10"%>
                </p>
                <p>  
                <p> 
                    <%= f.label :sched_date_field, "Deadline" %>
                    <%= f.datetime_field :completed_at, :class => "datepicker form-control"  %>
                </p>
                
                <p> 
                    <%= f.hidden_field :category_id ,class: "form-control", size: "30x10", value: @category_id.id%>
                </p>
                <p> 
                    <%= f.submit class: "btn btn-primary my-2"%>
                </p>

            <% end%>
              </div>
      </div>
    </div>
  </section>
</main>

app/views/tasks/show.html.erb
<%= link_to show_tasks_path(@category_id,user_id: @user_id) do%>
    <i class="fas fa-backward"></i>
<% end %>   
 <div class="card text-center">
  <div class="card-header">
    <%=  @category_id.name%>
  </div>
  <div class="card-body">
    <h5 class="card-title">Task</h5>
    <p class="card-text"> <h1> <%= @task_id.description%></h1></p>
    <a href="#" class="btn btn-primary"><%= @task_id.completed%>Click if done</a>
  </div>
  <div class="card-footer text-muted">
    Deadline:
    <%= @task_id.completed_at%>
  </div>
</div>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>