config/routes.rb
Rails.application.routes.draw do
  root 'users#home'
  get 'tasks/show:id', to: 'tasks#show', as: 'show_task'
  get 'task/new/:id', to: 'tasks#new' , as: 'tasks_new_id'
  get 'tasks/edit/:id' , to: 'tasks#edit' , as: 'edit_task'
  post 'tasks/update/:id' , to: 'tasks#update' , as: 'tasks_update'
  delete 'tasks/destroy/:id' , to: 'tasks#destroy' , as: 'destroy_task'
  post 'tasks/create/:id', to: 'tasks#create' , as: 'create_task'

  get '/today_tasks/:id', to: 'today_tasks#index', as: 'today_tasks'

  get 'categories/new/:id', to: "categories#new" , as: 'categories_new'
  get 'categories/:id', to: 'categories#show', as: 'show_tasks'
  post 'categories/create/:id', to: 'categories#create', as: 'categories_create'
  get 'categories/edit/:id', to: 'categories#edit' , as: 'categories_edit'
  post 'categories/update/:id', to: 'categories#update' , as: 'categories_update'
  # get 'categories/destroy'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
 

  get  '/home',   to: 'users#home', as: "home"

   
  resources :users

end

app/models/user.rb
class User < ApplicationRecord
    validates :username, presence: true, uniqueness: true
    validates :password, length: { in: 6..12 } 
    has_secure_password

    has_many :categories
    has_many :categories, through: :task
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  require 'date'
  before_action :logged_in_user, only: [:show]
    def show
        time = Time.now 
        @user = User.find(params[:id])
        @products_of_company = Category.where(user_id: params[:id])
        @user_id = User.find(params[:id])
        @categories = Category.joins(:user).where(:user => @user_id)
        @category = Category.joins(:user).where(:user => @user_id)
        @today_task_count = Task.where("DATE(completed_at) = ?", time.strftime("%Y-%m-%d") ).count
        @category_count = Category.joins(:user).where(:user => @user).count
    end
    def new
        @user = User.includes(:categories, :tasks)
        @user_new = User.new
    end
    def create
        @user = User.create(user_params)
         if @user.save 
          flash[:success] = "Welcome to the app!"
          redirect_to @user
         else
          render 'new'
         end
    end
    def user_params
         params.require(:user).permit(:username, :password)
    end
    def home
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/home.html.erb
<div class="card1 pb-5">
    <div class="row px-3 justify-content-center mt-4 mb-5 border-line"> <%= image_tag("Cohort analysis.gif", :alt => "rss feed") %></div>
    </div>
</div>
<div class="text-center">
    <h1>TODO App @Avion School</h1>
    <small class="text-muted">
        @alright reserve 2021-2022
    </small>
</div>

app/views/users/new.html.erb
  <% flash.each do |key, message| %>
  <div class="alert <%= flash_class(key) %> alert-dismissible fade show text-center" role="alert">
    <%= message %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<h1 class='text-center'>Sign up</h1>

<div class="row">
  <div class="col-md-4 offset-4">
    <%= form_with(model: @user_new, local: true) do |f| %>

      <%= f.label :username %>
      <%= f.email_field :username, class: 'mb-1 form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'mb-1 form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'mb-1 form-control'%>

      <%= f.submit "Create my account", class: "mt-2 btn btn-primary" %>
    <% end %>
  </div>
</div>
      <div class="card1 pb-5">
        <div class="row px-3 justify-content-center mt-4 mb-5 border-line"> <img src="https://i.imgur.com/uNGdWHi.png" class="image"> </div>
        </div>
    </div>

app/views/users/show.html.erb
<% flash.each do |key, message| %>
  <div class="alert <%= flash_class(key) %> alert-dismissible fade show text-center" role="alert">
    <%= message %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<p>
  <strong>Username:</strong>
  <%= @user_id.username %>
</p>
<p id="notice"><%= notice %></p>
<div class="container">
    <div class="text-center">
<h1>Categories</h1>
</div>
  <h4>Add Category 
     <%= link_to categories_new_path(@user_id), class: "btn btn-primary" do %>
     <i class="fas fa-plus"></i>    
    <%end%></h4> 
  <div class="table-responsive"> 
           
    <table class="table table-striped">
    <thead>
    <tr>
      <th>Category name</th>
      <th colspan="3"></th>
    </tr>
    </thead>
  <tbody>
      <% if(@category_count == "nil") %>
            <tr>
              <td>No Category</td>
              <td></td>
            </tr>  
        <% else %>
           <% @category.each do |category| %>
            <tr>
              <td><%= category.name %></td>
              <td><%= link_to show_tasks_path(category.id,user_id: @user_id) do %>
                    Tasks <i class="fa fa-tasks" aria-hidden="true"></i>
                  <% end %>
              </td>
              <td>
            </tr>
            
           <% end %>
            
      <% end %>
  </tbody>
  </table>
  </div>
</div>
