config/routes.rb
Rails.application.routes.draw do
  root 'users#home'
  get 'tasks/show:id', to: 'tasks#show', as: 'show_task'
  get 'task/new/:id', to: 'tasks#new' , as: 'tasks_new_id'
  get 'tasks/edit/:id' , to: 'tasks#edit' , as: 'edit_task'
  post 'tasks/update/:id' , to: 'tasks#update' , as: 'tasks_update'
  delete 'tasks/destroy/:id' , to: 'tasks#destroy' , as: 'destroy_task'
  post 'tasks/create/:id', to: 'tasks#create' , as: 'create_task'

  get '/today_tasks/:id', to: 'today_tasks#index', as: 'today_tasks'

  get 'categories/new/:id', to: "categories#new" , as: 'categories_new'
  get 'categories/:id', to: 'categories#show', as: 'show_tasks'
  post 'categories/create/:id', to: 'categories#create', as: 'categories_create'
  get 'categories/edit/:id', to: 'categories#edit' , as: 'categories_edit'
  post 'categories/update/:id', to: 'categories#update' , as: 'categories_update'
  # get 'categories/destroy'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
 

  get  '/home',   to: 'users#home', as: "home"

   
  resources :users

end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, :description, presence: true

    belongs_to :user
    has_many :task
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  require 'date'
  def new
    time = Time.now 
    @user_id = User.find(params[:id])
    @today_task_count = Task.where("DATE(completed_at) = ?", time.strftime("%Y-%m-%d") ).count
  end

  def show
    time = Time.now 
    @category = Category.find(params[:id])  
    @categories = Category.joins(:task)
    @tasks = Task.joins(:category).where( :categories => @category )
    @user_id = User.find(params[:user_id]) 
    time = Time.now 
    @today_task_count = Task.where("DATE(completed_at) = ?", time.strftime("%Y-%m-%d") ).count
  end

  def create
    time = Time.now 
    @today_task_count = Task.where("DATE(completed_at) = ?", time.strftime("%Y-%m-%d") ).count
    @category = User.find(params[:id])
    category_create = Category.create(name: params[:name], description: params[:description], user_id: params[:user_id] )

    if category_create.save
      redirect_to user_path(@category), :flash => { :success => "Successfull added new Category" }
      else
        redirect_to user_path(@category), :flash => {:alert => "Unabled to add Category"}
    end
  end

  def edit
    @user_id = User.find(params[:user_id])
    @category = Category.find(params[:id])
    @categories =  Category.where(:id => @category)
  end

  def update
    @user_id = User.find(params[:user_id])
    @category = Category.find(params[:id])
    @category.update(name: params[:name], description: params[:description])
    redirect_to show_tasks_path(@category,user_id:@user_id), :flash => { :success => "Successfully updated"}
  end

  def destroy
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<main>
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
           <h1>Edit Category </h1>
            <%= form_with url: categories_update_path(@category,user_id:@user_id) do |f| %>
            <div class="form-group">
                <% @categories.each do |category| %>
                <p> 
                    <%= f.label :name %> <br/>
                    <%= f.text_field :name ,class: "form-control", value: category.name %>
                </p>
                <p> 
                    <%= f.label :description %> <br/>
                    <%= f.text_area :description,class: "form-control", value: category.description %>
                </p>
                <p> 
                    <%= f.submit class: "btn btn-primary" %>
                </p>
            </div>
                <% end %>
            <% end %>
      </div>
    </div>
  </section>
</main>

app/views/categories/new.html.erb
<main>
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">      
        <h1>Create Category</h1>
            <%= form_with url: categories_create_path do |f| %>
                <div class="form-group">
                <p> 
                    <%= f.label :name %> <br/>
                    <%= f.text_field :name, class: "form-control"%>
                </p>
                <p> 
                    <%= f.label :description %> <br/>
                    <%= f.text_area :description ,class: "form-control", size: "30x10"%>
                </p>
                <p> 
                    <%= f.hidden_field :user_id ,class: "form-control", size: "30x10", value: @user_id.id%>
                </p>
                <p> 
                    <%= f.submit class: "btn btn-primary my-2"%>
                </p>

            <% end%>
              </div>
      </div>
    </div>
  </section>
</main>

app/views/categories/show.html.erb
<% flash.each do |key, message| %>
  <div class="alert <%= flash_class(key) %> alert-dismissible fade show text-center" role="alert">
    <%= message %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
    <div class="text-center">
        <h1>
          <%= @category.name%>
        </h1>
      
        <small class="text-muted"><%= @category.description%></small>
          <%= link_to categories_edit_path(@category.id,user_id:@user_id),class:"border-0 btn-transition btn btn-outline-success" do %>
          <i class="fa fa-edit"></i>
          <%end%>
    </div>
  <h4>Tasks  
  <%= link_to tasks_new_id_path(user_id:@user_id),class:"border-0 btn-transition btn btn-outline-primary" do %>
          <i class="fa fa-plus"></i>
  <%end%></h4>
           <div class="widget-content-right"> <button class="border-0 btn-transition btn btn-outline-success"> <i class="fa fa-check"></i></button> </div>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>completed</th>
        <th>Description</th>
        <th colspan="3">action</th>
      </tr>
    </thead>

    <tbody>
        
      <% @tasks.each do |task| %>
        <tr>
          <td><%= check_box_tag("name", "value", false, class: "checkbox") %></td>
          <td><%= task.description %></td>
          <td><%= link_to show_task_path(task,category_id:@category,user_id:@user_id),class:"border-0 btn-transition btn btn-outline-primary" do %>
          <i class="fa fa-eye"></i>
          <%end%></td></td>
          <td><%= link_to edit_task_path(task,category_id:@category,user_id:@user_id),class:"border-0 btn-transition btn btn-outline-success" do %>
          <i class="fa fa-edit"></i>
          <%end%></td>
          <td>
          <%= link_to  destroy_task_path(task,category_id:@category,user_id:@user_id), method: :delete, data: { confirm: 'Are you sure?' } ,class:"border-0 btn-transition btn btn-outline-danger" do %>
          <i class="fa fa-trash"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  

<!-- Modal -->

  <br>
  <%# <%= link_to 'Back', categories_path %>

</div>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>