config/routes.rb
Rails.application.routes.draw do
  root 'users#home'
  get 'tasks/show:id', to: 'tasks#show', as: 'show_task'
  get 'task/new/:id', to: 'tasks#new' , as: 'tasks_new_id'
  get 'tasks/edit/:id' , to: 'tasks#edit' , as: 'edit_task'
  post 'tasks/update/:id' , to: 'tasks#update' , as: 'tasks_update'
  delete 'tasks/destroy/:id' , to: 'tasks#destroy' , as: 'destroy_task'
  post 'tasks/create/:id', to: 'tasks#create' , as: 'create_task'

  get '/today_tasks/:id', to: 'today_tasks#index', as: 'today_tasks'

  get 'categories/new/:id', to: "categories#new" , as: 'categories_new'
  get 'categories/:id', to: 'categories#show', as: 'show_tasks'
  post 'categories/create/:id', to: 'categories#create', as: 'categories_create'
  get 'categories/edit/:id', to: 'categories#edit' , as: 'categories_edit'
  post 'categories/update/:id', to: 'categories#update' , as: 'categories_update'
  # get 'categories/destroy'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
 

  get  '/home',   to: 'users#home', as: "home"

   
  resources :users

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Journal4</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <script src="https://code.iconify.design/1/1.0.7/iconify.min.js"></script>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <style>
.page-todo .tasks {
    background: #fff;
    padding: 0;
    border-right: 1px solid #d1d4d7;
    margin: 10px 50px 30px 100px
}

.page-todo .task-list {
    padding: 100px 15px;
    height: 100%
}

.page-todo .graph {
    height: 100%
}

.page-todo .priority.high span {
    background: #f86c6b;
    padding: 2px 10px;
    color: #fff;
    display: inline-block;
    font-size: 12px
}
.page-todo .task.high {
    border-left: 2px solid #f86c6b
}

</style>
  </head>
  <nav class="navbar navbar-expand-md navbar-dark bg-info">
    <a class="navbar-brand" href="#">TODO-APP</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <% if !logged_in?%>
                <%= link_to "Home", home_path, class: "nav-link" %>
                <%else%>
                <%= link_to "Categories", user_path(@user_id), class: "nav-link" %>
                <li class="nav-item">
                   <%= link_to today_tasks_path(@user_id), class: "nav-link" do %>
                   Today tasks
                    <% if @today_task_count == 0%>
                    <i class="fas fa-bell"></i>
                    <%else%>
                    <i class="fas fa-bell"><b style="color:red;top:10px; position:absolute;"><%= @today_task_count %></b></i>
                   <%end%> 
                   <%end%>
                   
                    
                </li>
                <%end%>
            </li>
            
            <%# <li class="nav-item">
                <a class="nav-link" href="#">About Us</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Contact Us</a>
            </li> %>
        </ul>
        <ul class="navbar-nav">
        
       <% if logged_in? %>
        <ul class="nav navbar-right ">
            <li><%= link_to logout_path, method: :delete, class: "nav-link" do%>
              Sign-Out  <i class="fas fa-sign-out-alt"></i>
              <%end%>
            </li> 
            
        </ul>
        <% else %>
        <ul class="nav navbar-right ">
            <li><%= link_to "Log in", login_path, class: "nav-link" %></li> 
            <li><%= link_to "Sign up", new_user_path, class: "nav-link" %></li>
        </ul>
        <% end %>
        </ul>
    </div>
</nav>
<nav class="navbar mb-2">
  <div class="container-fluid">

  </div>
</nav>

  <body>
    <div class="container-sm">
    <%= yield %>
    </div>
  </body>
  <script type='text/javascript'>document.addEventListener('DOMContentLoaded', function () {window.setTimeout(document.querySelector('svg').classList.add('animated'),1000);})</script>
</html>